FROM ubuntu:18.04
MAINTAINER Jonathan Lifflander <jliffla@sandia.gov>

RUN apt-get update && apt-get install -y \
  curl \
  cmake \
  git \
  googletest \
  libmpich-dev \
  wget \
  gcc-5 \
  zlib1g \
  zlib1g-dev \
  libopenmpi-dev \
  ninja-build

COPY . /usr/src/checkpoint/

WORKDIR /usr/src

RUN \
 dpkg -L zlib1g && \
 export CC=mpicc && \
 export CXX=mpicxx && \
 if [ -d "googletest" ]; then rm -Rf googletest; fi && \
 if [ -d "detector" ]; then rm -Rf detector; fi && \
 git clone -b release-1.8.1 --depth 1 https://github.com/google/googletest.git && \
 export GTEST=$PWD/googletest && \
 export GTEST_BUILD=/usr/build/googletest && \
 export CHECKPOINT=$PWD/checkpoint && \
 export CHECKPOINT_BUILD=/usr/build/checkpoint && \
 git clone -b master --depth 1 https://github.com/DARMA-tasking/detector.git && \
 export DETECTOR=$PWD/detector && \
 export DETECTOR_BUILD=/usr/build/detector && \
 mkdir -p $DETECTOR_BUILD && \
 mkdir -p $GTEST_BUILD && \
 mkdir -p $CHECKPOINT_BUILD && \
 echo $SOURCE_COMMIT && \
 cd $GTEST_BUILD && \
 mkdir build && \
 cd build && \
 cmake -DCMAKE_INSTALL_PREFIX=$GTEST_BUILD/install -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC $GTEST && \
 make && \
 make install && \
 cd $DETECTOR_BUILD && \
 mkdir build && \
 cd build && \
 cmake -DCMAKE_INSTALL_PREFIX=$DETECTOR_BUILD/install -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC  $DETECTOR && \
 make && \
 make install && \
 cd $CHECKPOINT_BUILD && \
 mkdir build && \
 cd build && \
 cmake -Dgtest_DIR=$GTEST_BUILD/install -DGTEST_ROOT=$GTEST_BUILD/install -DCHECKPOINT_BUILD_TESTS:BOOL=1 -DCMAKE_INSTALL_PREFIX=$CHECKPOINT_BUILD/install -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC -Ddetector_DIR=$DETECTOR_BUILD/install  $CHECKPOINT && \
 make && \
 make install && \
 make test

COPY $DETECTOR_BUILD/ $DETECTOR_BUILD
COPY $CHECKPOINT_BUILD/ $CHECKPOINT_BUILD
COPY $GTEST_BUILD/ $GTEST_BUILD
