ARG REPO=lifflander1/vt
ARG ARCH=amd64
ARG IMAGE=wf-amd64-ubuntu-22.04-gcc-12-cpp
ARG BASE=${REPO}:${IMAGE}

FROM --platform=${ARCH} ${BASE} AS build

ARG CMAKE_BUILD_TYPE
ARG CMAKE_CXX_STANDARD
ARG CODE_COVERAGE
ARG MAGISTRATE_TESTS_ENABLED
ARG MAGISTRATE_EXAMPLES_ENABLED
ARG MAGISTRATE_MPI_ENABLED
ARG MAGISTRATE_WARNINGS_AS_ERRORS
ARG MAGISTRATE_DOXYGEN_ENABLED
ARG MAGISTRATE_ASAN_ENABLED
ARG MAGISTRATE_UBSAN_ENABLED
ARG MAGISTRATE_SERIALIZATION_ERROR_CHECKING_ENABLED
ARG MAGISTRATE_BUILD_AGAINST_VT
ARG IMAGE
ARG CI_CCACHE_DIR

ENV CI_CCACHE_DIR=${CI_CCACHE_DIR}

RUN --mount=type=cache,id=ccache-${IMAGE},target=/build/ccache \
    --mount=target=/magistrate,rw \
    if [ -d /magistrate/docker-output/build/ci/ccache ]; then \
        cp -a /magistrate/docker-output/build/ci/ccache/. /build/ccache/; \
    fi && \
    if [ "$MAGISTRATE_BUILD_AGAINST_VT" = "1" ]; then \
        /magistrate/ci/build_against_vt.sh /vt /build /magistrate; \
    else \
        /magistrate/ci/build_cpp.sh /magistrate /build; \
    fi && \
    /magistrate/ci/test_cpp.sh /magistrate /build

FROM scratch AS artifacts
COPY --from=build /build/ /build/
