name: magistrate-docs

on:
  push:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - uses: docker/bake-action@v6
        with:
          source: .
          targets: magistrate-docs
          files: docker-bake.hcl
          push: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
