name: Check License and Header Guards

on: pull_request

jobs:
  check:
    name: Check License/Guards
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libfile-find-rule-perl

    - name: Check license and header guards
      shell: bash
      run: ./scripts/check_guards.sh $(pwd) true
